### ISSUE TITLE
Actions 日志暴露个人信息

### ISSUE THREAD

**Issue by chiupam** [287857652/yiban-autocheck-csust#3]
我建议你注释掉 main.py 第51行

```py
            if submit_result["code"] == 0:
                share_url = yb.getShareUrl(submit_result["data"])["data"]["uri"]
                print("已完成一次体温上报[%s]" % task_detail["Title"])
                # print("访问此网址查看详情：%s" % share_url)
                title='已完成一次签到'
                message=share_url
                api = 'https://sc.ftqq.com/%s.send'%SCKEY
                data ={
                        "text" : title,
                        "desp" : message
                      }
                req = requests.post(api, data=data)        
            else:
                print("[%s]遇到了一些错误:%s" % (task_detail["Title"], submit_result["msg"]))
```

因为如果你 print() 出来大家可以从 share_url 中查到你的全部个人信息

**Comment by chiupam** [comment]
以及第17行

```py
    try:
        yb = YiBan(PHONE,PASS) # FIXME:账号密码
        yb.login()
        yb.getHome()
        # print("登录成功 %s"%yb.name)
        yb.auth()
        all_task = yb.getUncompletedList()["data"]
        all_task = list(filter(lambda x: "体温检测" in x["Title"], all_task))  # FIXME: 长理的打卡任务标题均含有"体温检测"字样 此举是防止其他表单干扰 （可能会变）
```

**Comment by 287857652** [comment]
啊这，没怎么玩github才知道能直接访问别人的action日志啊，......
感谢，已经修改了

**Comment by chiupam** [comment]
还想提醒你删除 Actions 日志的 结果发现你挺机智 已经自行删除了 这么多日志幸苦了吧 哈哈哈
同时针对 `auto.yml` 文件我给你推荐了一下写法 修改的地方都有注释 望对你有一定的帮助

```yml
name: yiban autocheck csust

on:
  workflow_dispatch:
  # push: # 注释掉后仓库有 update 时不执行 main.py
  schedule:
   - cron: "0 0,1,6,7 * * *"  # scheduled at 8:00、9:00、14:00、15:00(UTC+8) everyday （但事实上UTC+8的8点很难准时，往往会排队到9点多）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # 使用 python 3.x 最新版本

      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai' # 设置时区为中国/上海

      - name: Install dependencies
        run: 
          pip install -r requirements.txt

      - name: Working
        env: 
          SCKEY: ${{ secrets.SCKEY }}
          PHONE: ${{ secrets.PHONE }}
          PASS: ${{ secrets.PASS }}
        run: |
          python main.py 
```
